on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: aws-secret

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Zip application
        run: |
          zip -r app.zip . -x "*.git*" "test/*"

      - name: Configure AWS credentials manually
        run: |
          mkdir -p ~/.aws
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials
          echo "aws_session_token = ${{ secrets.AWS_SESSION_TOKEN }}" >> ~/.aws/credentials
          echo "[default]" > ~/.aws/config
          echo "region = us-east-1" >> ~/.aws/config

      - name: Debug AWS credentials
        run: cat ~/.aws/credentials
          
      - name: Upload to S3
        run: |
          aws s3 cp app.zip s3://app-werayuth/app-${{ github.sha }}.zip

      - name: Create new application version
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name "${{ secrets.EB_APP_NAME }}" \
            --version-label "${{ github.sha }}" \
            --source-bundle S3Bucket="${{ secrets.S3_BUCKET }}",S3Key="app-${{ github.sha }}.zip"

      - name: Deploy to Elastic Beanstalk environment
        run: |
          aws elasticbeanstalk update-environment \
            --environment-name "${{ secrets.EB_ENV_NAME }}" \
            --version-label "${{ github.sha }}"
